import { Theme } from "@rainbow-me/rainbowkit";
export const rainbowKitTheme: Theme = {
  blurs: {
    modalOverlay: "...",
  },
  colors: {
    accentColor: "#58C6AA",
    accentColorForeground: "#ffffff",
    actionButtonBorder: "transparent",
    actionButtonBorderMobile: "transparent",
    actionButtonSecondaryBackground: "#81D4BF",
    closeButton: "#ffffff",
    closeButtonBackground: "transparent",
    connectButtonBackground: "#58C6AA",
    connectButtonBackgroundError: "#BC0030",
    connectButtonInnerBackground: "#58C6AA",
    connectButtonText: "#ffffff",
    connectButtonTextError: "#ffffff",
    connectionIndicator: "#81D4BF",
    downloadBottomCardBackground: "#747c90",
    downloadTopCardBackground: "#839bbd",
    error: "#525c76",
    generalBorder: "transparent",
    generalBorderDim: "#81D4BF",
    menuItemBackground: "#81D4BF",
    modalBackdrop: "rgba(0, 0, 0, 0.5)",
    modalBackground: "#58C6AA",
    modalBorder: "transparent",
    modalText: "#ffffff",
    modalTextDim: "rgba(255, 255, 255, 0.6)",
    modalTextSecondary: "rgba(255, 255, 255, 0.6)",
    profileAction: "#81D4BF",
    profileActionHover: "#81D4BF",
    profileForeground: "#58C6AA",
    selectedOptionBorder: "transparent",
    standby: "#f9f8ff",
  },
  fonts: {
    body: "Inter",
  },
  radii: {
    actionButton: "20px",
    connectButton: "10px",
    menuButton: "3px",
    modal: "8px",
    modalMobile: "13.5px",
  },
  shadows: {
    connectButton: "0px 4px 4px rgba(0, 0, 0, 0.25)",
    dialog:
      "4px 4px 10px rgba(0,0,0,0.24), 2px 2px 4px rgba(0, 0, 0, 0.12),1px 2px 2px rgba(0, 0, 0, 0.12)",
    profileDetailsAction: "...",
    selectedOption: "...",
    selectedWallet: "...",
    walletLogo: "...",
  },
};
